name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".**"
      - "docs/**"

jobs:
  build:
    name: Dockerイメージをbuildし、レジストリにpushする
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Dockerイメージをbuild & push
        id: publish_docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: faruryo/pixi-practice
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
